language: python
python:
  - "3.6"
script:
  - git clone https://github.com/Cantera/cantera ../cantera
  - git clone https://github.com/Cantera/cantera-jupyter ../cantera-jupyter
  - NIKOLA_DEBUG=1 nikola build
